# MySQL's connection details
mysql:
  enabled: false # Should MySQL be enabled? If false, SQLite will be used instead.
  driver: 'com.mysql.cj.jdbc.Driver' # The driver to use, defaults to 'com.mysql.jdbc.Driver'.
  host: 'localhost' # Hostname of the MySQL server, defaults to 'localhost'
  port: 3306 # Database port, 3306 is the default
  username: root # Username to connect to the MySQL server, defaults to 'root'
  password: 'password' # Password to connect to the MySQL server, defaults to 'password'
  ssl: false # Should SSL be used? Defaults to false
  database: privatemessages # Database to use, defaults to 'privatemessages'
message-sound:
  key: 'entity.experience_orb.pickup' # The sound to play when a message is received
  source: 'PLAYER' # The source of the sound
  volume: 1.0 # The volume of the sound
  pitch: 1.0 # The pitch of the sound
anti-swear:
  enable-caps-filter: true # Should the caps filter be enabled?
  enable-swear-filter: true # Should the swear filter be enabled?
  caps-percent: 50 # The percentage of caps in a message to trigger the filter
  swear-regex: '(?i)(f|ph)(u|o|a)(c|k|q)(k|q)' # The regex to use to detect swears
# Commands section
commands:
  reload:
    name: reload
    permission: 'privatemessages.command.reload'
  message:
    name: message
    permission: 'privatemessages.command.message'
    aliases:
      - m
      - msg
      - w
      - whisper
      - tell
      - t
      - msg
  reply:
    name: reply
    permission: 'privatemessages.command.message'
    aliases:
      - r
  ignore:
    name: ignore
    permission: 'privatemessages.command.ignore'
    aliases:
      - ignores
    add:
      name: add
      permission: 'privatemessages.command.ignore'
    remove:
      name: remove
      permission: 'privatemessages.command.ignore'
    list:
      name: list
      permission: 'privatemessages.command.ignore'
      max-size: 10
  toggle-messages:
    name: togglemessages
    permission: 'privatemessages.command.toggle'
    aliases:
      - toggle-messages
  toggle-sound:
    name: togglesound
    permission: 'privatemessages.command.toggle'
    aliases:
      - toggle-sound
  social-spy:
    name: socialspy
    permission: 'privatemessages.command.socialspy'
    aliases:
      - social-spy
servers-configuration:
  lobby:
    display-name: '&cLobby'